<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
    <title>Completed tasks</title>
</head>
<body>

<h1>Completed tasks</h1>

<?php
foreach ($tasks as $task) {
    echo '<span>' . $task['task_name'] . '</span>' . ' <form action="/completedTasks/' . $task['id'] . '" method="get"><input type="submit" value="X">' . '<br>';
}
?>

<p><a href="/">Go back to tasks</a></p>
</body>
</html>