<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            /*margin: 50px 0 0 0;*/
            /*padding: 0;*/
            /*width: 100%;*/
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        .completedTaskDiv {
            box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px;
        }

        a {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #111185;
            font-size: 18px;
            text-decoration: none;
        }

        a:hover {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #111185;
            font-size: 18px;
            text-decoration: none;
            font-weight: bold;
        }
    </style>
    <title>Completed tasks</title>
</head>
<body>
<div class="container text-center d-flex p-5 flex-column my-5 completedTaskDiv">
    <h1>Completed tasks</h1><br>

    <?php
    foreach ($tasks as $task) {
        echo '<div class="container d-flex justify-content-center">' . '<span class="me-2">' . $task['task_name'] . '</span>' . ' <form action="/completedTasks/' . $task['id'] . '" method="get"><input type="submit" value="X">' . '</div>' . '<br>';
    }
    ?>

    <p><a href="/">Go back to tasks</a></p>
</div>
</body>
</html>