<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h2 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        a {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #111185;
            font-size: 18px;
            text-decoration: none;
        }

        a:hover {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #111185;
            font-size: 18px;
            text-decoration: none;
            font-weight: bold;
        }

        .editTaskDiv {
            box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px;
        }

    </style>
    <title>Edit Task</title>
</head>
<body>
<div class="editTaskDiv container text-center d-flex justify-content-center flex-column p-5">
    <h2>Edit task</h2><br>
    <form action="/editTask/<?= $id ?>" method="post">
        <label for="editTask">Edit task:</label>
        <input class="border border-2 rounded border-success border-opacity-50" id="editTask" type="text"
               name="editTask" value="<?= $editText ?>">
        <input class="border border-2 rounded border-success border-opacity-50" type="submit" value="Update task"/>
    </form>
    <br>
    <p><a href="/">Go back to tasks</a></p>
</div>
</body>
</html>