<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
    <title>Edit Task</title>
</head>
<body>
<h2>Edit task</h2>
<form action="/editTask/<?=$id?>" method="post">
    <label for="editTask">Edit task:</label>
    <input id="editTask" type="text" name="editTask" value="<?=$editText?>">
    <br>
    <input type="submit" value="Update task"/>
</form>
<p><a href="/">Go back to tasks</a></p>
</body>
</html>